parameters:
#    transilien_service_transilien_controller.example.class: TransilienService\TransilienControllerBundle\Example

services:
#    transilien_service_transilien_controller.example:
#        class: %transilien_service_transilien_controller.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
